#!/bin/bash
read a
read b
read c
if [ $((a+b)) -gt $c ] || [ $((b+c)) -gt $a ] || [ $((c+a)) -gt $b ]
then
    if [ $a -eq $b ] && [ $a -eq $c ]
    then
        echo "EQUILATERAL"
    elif [ $a -ne $b ] && [ $b -ne $c ] && [ $c -ne $a ]
    then
        echo "SCALENE"
    else
        echo "ISOSCELES"
fi
fi
